### ISSUE TITLE
Required environment variable missing, or value not allowed

### ISSUE THREAD

**Issue by intelligence** [roots/wp-cli-theme-activation#4]
While trying to run `wp theme activation` I recieved this error message:

```
Fatal error: Uncaught exception 'RuntimeException' with message 'Required environment variable missing, or value not allowed: 'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL'' in /Users/user/WWW/project/project.dev/vendor/vlucas/phpdotenv/src/Dotenv.php:106
Stack trace:
#0 /Users/user/WWW/project/project.dev/config/application.php(12): Dotenv::required(Array)
#1 phar:///usr/bin/wp/php/wp-cli.php(18) : eval()'d code(7): require_once('/Users/persture...')
#2 phar:///usr/bin/wp/php/wp-cli.php(18): eval()
#3 phar:///usr/bin/wp/php/boot-phar.php(5): include('phar:///usr/bin...')
#4 /usr/bin/wp(4): include('phar:///usr/bin...')
#5 {main}
  thrown in /Users/user/WWW/project/project.dev/vendor/vlucas/phpdotenv/src/Dotenv.php on line 106
```

**Comment by QWp6t** [comment]
Error doesn't have anything to do with theme activation.

Looks like you got a busted bedrock installation. Populate your `.env` file in Bedrock. Or simply use this separate from Bedrock.
